### ISSUE TITLE
Navigating is slower than 3.x.x

### ISSUE THREAD

**Issue by ferrannp** [react-navigation/navigation-ex#78] opened 2019-08-28 10:18 UTC
Both examples are in Debug mode. Notice the time to transition when you click the number 28. This is master:

![master](https://user-images.githubusercontent.com/774577/63847256-bb369900-c98d-11e9-853d-bcc30fc5d9e5.gif)

This is from PR https://github.com/ferrannp/fithero/pull/132:

![pr](https://user-images.githubusercontent.com/774577/63847326-da352b00-c98d-11e9-9bce-ba116a57bf16.gif)

**Comment by osdnk** [comment] 2019-08-28 10:37
rather fixed

**Comment by ferrannp** [comment] 2019-08-28 16:03
I tried and it does not feel better with `5.0.0-alpha.7`.

**Comment by osdnk** [comment] 2019-08-29 09:42
Can you thy with `5.0.0-alpha.8`?

**Comment by jsamr** [comment] 2019-10-11 12:50
I have the same issue. There is easily a 2 seconds delay between "back button" press and pop action. `@react-navigation/core@5.0.0-alpha.14`, `@react-navigation/native@5.0.0-alpha.11`. I could reproduce the same issue on stack navigator and top tab navigator. However, on stack navigator, the "push" is fast, and I face the issue only when popping a screen.

**Comment by satya164** [comment] 2019-10-11 12:56
@jpaas can you provide a demo of your issue?

**Comment by jsamr** [comment] 2019-10-11 13:13
@satya164 OK, going to work on a MWE

**Comment by jsamr** [comment] 2019-10-11 13:31
@satya164 The debug mode was responsible for delays on Android (hermes disabled).

**Comment by mattmogford** [comment] 2019-12-18 17:03
In general loading a new page on release with 5.0.0-alpha.23, is very slow for me. With minimal components on the loaded page.

**Comment by satya164** [comment] 2020-01-05 01:12
Closing since we've migrated to React Native Animated.

**Closed by satya164** 2020-01-05 01:12 UTC
Labels: package:stack
