### ISSUE TITLE
Previous Stack Header doesn't go away

### ISSUE THREAD

**Issue by kennetpostigo** [react-navigation/navigation-ex#92] opened 2019-09-01 18:25 UTC
I recently noticed that sometimes stack headers don't go away, the previous stack header remains behind the current/new one, you can see it because they have different background colors and heights.

![image](https://user-images.githubusercontent.com/8888991/64080598-42ed1200-ccc4-11e9-900d-dd5f51721ccd.png)

**Comment by brentvatne** [comment] 2019-09-17 20:41
@kennetpostigo - can you provide a reproducible example?

**Comment by satya164** [comment] 2019-09-17 20:52
This was because the header was custom with `headerMode: 'screen'` and didn't handle the animations. Closing.

**Closed by satya164** 2019-09-17 20:52 UTC
