### ISSUE TITLE
Going back with a gesture breaks navigation

### ISSUE THREAD

**Issue by radko93** [react-navigation/navigation-ex#256] opened 2020-01-07 20:08 UTC
**Current Behavior**
Running example from repo as of commit https://github.com/react-navigation/navigation-ex/commit/14cd7de6658b5a655e97f05f2e2c702abf470fba

1. Push a route in Stack Navigator
2. Come back with a gesture
3. Push the same route
4. Come back with a gesture
5. Try to again push the route -  pushing the route fails (new screen opens and then jumps back).

![ezgif com-gif-maker](https://user-images.githubusercontent.com/7029942/71926126-df538380-3192-11ea-91bf-415073e3b94d.gif)

When using the back button everything works fine.

**Expected Behavior**

Navigating always works as expected.

**Comment by satya164** [comment] 2020-01-07 23:36
I think this is because you're navigating to new screen before the gesture animation has settled (since spring animations take a while to settle). Since the animation hasn't finished yet, and the screen hasn't been popped yet, navigating to that screen brings the same screen again.

**Comment by radko93** [comment] 2020-01-08 09:04
@satya164 that's true, I was too fast. Still a bug IMO.

**Comment by lumyjuwon** [comment] 2020-01-08 16:02
@radko93 
i have found the solution.
according to satya164, the bug is because of spring animation.

the default ios gesture back animation transitionspecs is like
```
export const TransitionIOSSpec: TransitionSpec = {
  animation: 'spring',
  config: {
    stiffness: 1000,
    damping: 500,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 0.01,
    restSpeedThreshold: 0.01,
  },
};
```

as you can see, the transitionspec animation type of gesture back is 'spring'

when you change the transitionIOSSpec like 
```
IOSTransitionSpec = {
    duration: 250,
    easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
    timing: Animated.timing,
  };
```
the bug will be fixed.

or you can set your stack navigator options like
```
const config = {
    duration: 250,
    easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
    timing: Animated.timing,
}

<Stack.Screen
  component={Profile}
  options={{
    transitionSpec: {
      open: config,
      close: config,
    },
  }}
/>
```
i recommend the duration under 500, the duration will be longer than 500 you gesture back the screen but the close animation isn't finished so this will be like your gif.


@satya164 
the problem is okay under the react-navigation-stack(https://github.com/react-navigation/stack) 1.10.3 becuase of supplying the time animation.
**https://github.com/react-navigation/stack/blob/v1.10.3/src/views/StackView/StackViewTransitionConfigs.tsx**

```
let IOSTransitionSpec;
if (supportsImprovedSpringAnimation()) {
  // These are the exact values from UINavigationController's animation configuration
  IOSTransitionSpec = {
    timing: Animated.spring,
    stiffness: 1000,
    damping: 500,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 0.01,
    restSpeedThreshold: 0.01,
  };
} else {
  // This is an approximation of the IOS spring animation using a derived bezier curve
  IOSTransitionSpec = {
    duration: 500,
    easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
    timing: Animated.timing,
  };
}
```

but over react-navigation-stack v2 or navigation-ex/stack module don't supply the time animation.
**https://github.com/react-navigation/navigation-ex/blob/master/packages/stack/src/TransitionConfigs/TransitionSpecs.tsx**
```
export const TransitionIOSSpec: TransitionSpec = {
  animation: 'spring',
  config: {
    stiffness: 1000,
    damping: 500,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 0.01,
    restSpeedThreshold: 0.01,
  },
};
```

i think adding the time animation will be a tool to solve this bug.

**Comment by satya164** [comment] 2020-01-09 00:04
The spring animation makes it easier to see the issue, doesn't mean that the issue is because of spring animation. If you're fast enough with a timing animation, you'd see the same issue. The user can also provide a custom animation, so just changing the default animation isn't a fix.

Spring is also the correct animation to use here so that it provides a good experience when dismissing a screen with gesture. The issue needs to be addressed separately so that it works with all configs.

**Closed** 2020-01-09 01:42 UTC
Labels: bug, package:stack
